trigger:
- main

pool: 'my-personal-computer'

steps:
# Checkout the repository code
- checkout: self

# Set the CommitHash (full commit hash)
- script: |
    # Extract the last 4 digits of the commit hash
    shortCommitHash=$(echo $(Build.SourceVersion) | tail -c 5)
    echo "Using short commit hash: ${shortCommitHash}"
    
    # Set the variable for later use in the pipeline
    echo "##vso[task.setvariable variable=shortCommitHash]${shortCommitHash}"
  displayName: 'Set Commit Hash Variable'


# Copy the necessary files to the artifact staging directory (including Dockerfile)
- task: CopyFiles@2
  inputs:
    Contents: '**/Dockerfile'  # Ensure Dockerfile is copied
    TargetFolder: '$(Build.ArtifactStagingDirectory)'  # No subfolder

- task: CopyFiles@2
  inputs:
   Contents: | 
      **/*
   TargetFolder: '$(Build.ArtifactStagingDirectory)' 


# List files in Artifact Staging Directory for debugging
- script: |
    ls -la $(Build.ArtifactStagingDirectory)
  displayName: 'List files in Artifact Staging Directory'

# Build the Docker image and tag it with the commit hash
- task: Docker@2
  inputs:
    command: 'build'
    repository: 'johannyet/full_stack_2f_backend'
    Dockerfile: '$(Build.ArtifactStagingDirectory)/Dockerfile'  # Adjust as needed
    buildContext: '$(Build.ArtifactStagingDirectory)'  # No subfolder
    tags: '$(shortCommitHash)'  # This will now reference the short commit hash
    arguments: '--no-cache'

# Push the Docker image to Docker Hub
- task: Docker@2
  inputs:
    command: 'push'
    repository: 'johannyet/full_stack_2f_backend'
    tags: '$(shortCommitHash)'

- task: SSH@0
  displayName: 'Deploy to Docker Swarm'
  inputs:
    sshEndpoint: 'deploy'  # Your SSH service connection
    runOptions: 'inline'
    inline: |
      sudo docker service update -env-add CONFIG_PATH="/app/config.yml" --image johannyet/full_stack_2f_backend:$(shortCommitHash) backend_service