trigger:
- main

pool: 'my-personal-computer'

steps:
# Checkout the repository code
- checkout: self

# Set the CommitHash (full commit hash)
- script: |
    echo "##vso[task.setvariable variable=CommitHash]$(git rev-parse HEAD)"
  displayName: 'Set Full Commit Hash Variable'

# Copy the necessary files to the artifact staging directory (including Dockerfile)
- task: CopyFiles@2
  inputs:
    Contents: '**/Dockerfile'  # Ensure Dockerfile is copied
    TargetFolder: '$(Build.ArtifactStagingDirectory)'  # No subfolder

- task: CopyFiles@2
  inputs:
   Contents: | 
      go.sum 
      go.mod
   TargetFolder: '$(Build.ArtifactStagingDirectory)' 

- task: CopyFiles@2
  inputs:
    Contents: |
       go.mod
       go.sum
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# List files in Artifact Staging Directory for debugging
- script: |
    ls -la $(Build.ArtifactStagingDirectory)
  displayName: 'List files in Artifact Staging Directory'

# Build the Docker image and tag it with the commit hash
- task: Docker@2
  inputs:
    command: 'build'
    repository: 'johannyet/full_stack_2f_backend'
    Dockerfile: '$(Build.ArtifactStagingDirectory)/Dockerfile'  # Adjust as needed
    buildContext: '$(Build.ArtifactStagingDirectory)'  # No subfolder
    tags: '$(CommitHash)'

# Push the Docker image to Docker Hub
- task: Docker@2
  inputs:
    command: 'push'
    repository: 'johannyet/full_stack_2f_backend'
    tags: '$(CommitHash)'

# SSH into Docker Swarm manager and update the service
- task: SSH@0
  inputs:
    sshEndpoint: 'deploy'
    runOptions: 'inline'
    inline: |
      docker pull johannyet/full_stack_2f_backend:$(CommitHash)
      docker service update --image johannyet/full_stack_2f_backend:$(CommitHash) your_service_name
