trigger:
- main

pool: 'my-personal-computer'

steps:
# Checkout the repository code
- checkout: self

# Set the CommitHash (full commit hash)
- script: |
    echo "##vso[task.setvariable variable=CommitHash]$(git rev-parse HEAD)"
  displayName: 'Set Full Commit Hash Variable'

# Copy the necessary files to the artifact staging directory (including Dockerfile)
- task: CopyFiles@2
  inputs:
    Contents: '**/Dockerfile'  # Ensure Dockerfile is copied
    TargetFolder: '$(Build.ArtifactStagingDirectory)'  # No subfolder

- task: CopyFiles@2
  inputs:
   Contents: | 
      **/*
   TargetFolder: '$(Build.ArtifactStagingDirectory)' 


# List files in Artifact Staging Directory for debugging
- script: |
    ls -la $(Build.ArtifactStagingDirectory)
  displayName: 'List files in Artifact Staging Directory'

# Build the Docker image and tag it with the commit hash
- task: Docker@2
  inputs:
    command: 'build'
    repository: 'johannyet/full_stack_2f_backend'
    Dockerfile: '$(Build.ArtifactStagingDirectory)/Dockerfile'  # Adjust as needed
    buildContext: '$(Build.ArtifactStagingDirectory)'  # No subfolder
    tags: '$(CommitHash)'
    arguments: '--no-cache'

# Push the Docker image to Docker Hub
- task: Docker@2
  inputs:
    command: 'push'
    repository: 'johannyet/full_stack_2f_backend'
    tags: '$(CommitHash)'

- task: SSH@0
  displayName: 'Deploy to Docker Swarm'
  inputs:
    sshEndpoint: 'deploy'  # Your SSH service connection
    runOptions: 'inline'
    inline: |
      # Create or update Backend Service
      docker service create --name backend_service --replicas 2 --publish 5000:5000 johannyet/full_stack_2f_backend:$(CommitHash) || \
      docker service update --image johannyet/full_stack_2f_backend:$(CommitHash) backend_service