# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

pool: my-personal-computer

steps:
- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: GoTool@0
  inputs:
    version: '1.18.0'  # Specify the Go version directly

- script: |
    go version
    which go
  displayName: 'Check Go Version and Path'

- script: |
    go build
  displayName: 'Build with Go'
  workingDirectory: '$(Build.ArtifactStagingDirectory)/main'  # Adjust if necessary
