app:
  env: "local"

server:
  port: "8081"

db:
  driver: "cassandra" # dont touch it!
  name: "todoapp_db" # dont touch it!
  host: "localhost"
  port: "9042"
  user: ""
  password: "" 
  keyspace: ""
  contact_points: "localhost:9042"
  migrations_path: "db/migration/" # dont touch it!
